# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 10:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activity', '0002_auto_20161013_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityCategory')),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activity.ActivityType')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_filter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscriptions.SearchFilter')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
