# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='locations',
            field=models.ManyToManyField(through='activity.ActivityLocation', to='locations.Location'),
        ),
        migrations.AlterField(
            model_name='activitylocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.Location'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
