# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20160927_1450'),
        ('activity', '0002_auto_20161001_1008'),
    ]

    operations = [
    ]
