# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20161003_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
