# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='longtitude',
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(max_length=10),
        ),
    ]
