# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_auto_20161025_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='comment',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
