# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0005_participant_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
