# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0006_participant_participant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='comment_for_participant',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
