# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        ('locations', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CR', 'Created'), ('CO', 'Confirmed'), ('RE', 'Rejected')], default='CR', max_length=2)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('activity_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.ActivityCategory')),
                ('activity_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity.ActivityType')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.Location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.User')),
            ],
        ),
        migrations.AddField(
            model_name='confirmation',
            name='planned_activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.PlannedActivity'),
        ),
    ]
